---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-styles-cm
data:
  my-styles.css: |
    body{
      background: #933131;
    }
    .ui-banner {
      background: #933131;
    }
    .theme-light .top-bar {
      background: #93313180;
    }
    .theme-light .cd-layout {
      background-color: #cccccc;
    }
    .sidebar {
      background: #550000;
    }
    .top-bar {
      background: #933131;
    }
    .nav-bar {
      background: #933131;
    }
    .filters-group__panel {
      background-color: #933131;
      color: #933131;
    }
    .filter {
      background-color: #373737;
    }
    .filter__header {
      color: #ffffff;
    }
    .filter__item {
      background-color: #373737;
      color: #ffffff;
    }
    .filter__collapse {
      color: #ffffff;
    }
  namespace: argocd

